# Generated by Django 4.1.6 on 2023-03-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=80)),
                ('Lname', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
