# Generated by Django 4.1.3 on 2022-11-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Features',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('monitor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_api.room_features')),
            ],
        ),
    ]
